#! /bin/sh

bspc rule -r "*"

###---Autostart---###
xsetroot -cursor_name left_ptr &
[[ -f ~/.Xmodmap ]] && xmodmap ~/.Xmodmap &
xrdb ~/.Xresources &
polybar Cyfraka &
sxhkd &
dunst &

###---Monitors configuration---###
bspc monitor LVDS1 -d 1 2 3 4 5 6 7 8 9 0 

bspc config border_width         1
bspc config window_gap          10
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

### Xrandr
xrandr --output LVDS1 --primary --mode 1366x768 --rotate normal --output VGA1 --mode 1920x1080 --rotate normal --above LVDS1 &

###---Custom configuration---###

### Wallpaper
xwallpaper --zoom /home/cyfraka/arch-linux-wallpaper.png &

### Xresources
xrdb .Xresources

### Compton
#ipicom -b &
#picom -f & 

### Polybar
/home/cyfraka/.config/polybar/config.sh &

## Firefox
Firefox &
bspc rule -a Firefox desktop='^2' 

## Discord
#Discord &
bspc rule -a discord  desktop='^3' 


###---Global Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier lock
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color	"4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#406ea5"
bspc config presel_feedback_color "#5e81ac"
bspc config urgent_border_color "#dd2727"

###---Monitor And Desktop Settings----###
bspc config top_padding 25
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 5

###---Rules---###
bspc rule -a mpv state=fullscreen
bspc rule -a Zathura state=tiled
bspc rule -a Screenkey manage=off
